const mongoose = require('mongoose')
const Schema=mongoose.Schema

const profilesSchema=new Schema({
    user:{//关联数据表
        type:String,
        ref: 'users',//填写需要关联的表名
        require:true
    },
    handle:{
        type:String,
        require:true,
        max:40
    },
    company:{
        type:String,
    },
    website:{
        type:String,
    },
    location:{
        type:String,
        require:true
    },
    status:{
        type:String,
        require:true
    },
    skills:{
        type:[String],
        require:true
    },
    bio:{
        type:String,
    },
    githubusername:{
        type:String,
    },
    experience:[
        {
            current:{
                type:Boolean,
            },
            title:{
                type:String,
            },
            company:{
                type:String,
            },
            location:{
                type:String,
            },
            from:{
                type:String,
            },
            to:{
                type:String,
            },
            description:{
                type:String,
            },
        }
    ],
    education:[
        {
            current:{
                type:Boolean,
            },
            school:{
                type:String,
            },
            degree:{
                type:String,
            },
            fieldofstudy:{
                type:String,
            },
            from:{
                type:String,
            },
            to:{
                type:String,
            },
            description:{
                type:String,
            }
        }
    ],
    social:{
        wechat:{
            type:String,
        },
        QQ:{
            type:String,
        },
        tengxunkt:{
            type:String,
        },
        wangyikt:{
            type:String,
        }
    },

   date:{
        type:Date,
        default:Date.now
    }

})

module.exports=Profiles=mongoose.model('profiles',profilesSchema)